Main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render

def home(request):
    # your view logic here
    return render(request, 'home.html')  # adjust the template name as needed


def home(request):

    return render(request, 'base.html')  # adjust the template name as needed

urlpatterns = [
    path('admin/', admin.site.urls),
    path('forum/',home ,name = 'home'),
    path('', include('Post.urls', namespace="post")),
    path('profile/', include('allauth.urls')),
    path('ads/', include('advert.urls', namespace="advert")),
    path('comment/', include('Comment.urls', namespace="comment")),
]

advert/urls.py
from django.urls import path
from advert import views

app_name = "advert"
urlpatterns = [
    path('advert/', views.advert, name="advert"),
    path('checkout/', views.checkout, name="ad_checkout"),
    path('checked_out/', views.checked_out, name="checked_out"),
]

advert/models.py
from django.db import models

# Create your models here.

advert/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.conf import settings
import stripe
stripe.api_key = settings.STRIPE_SECRET_KEY
# Create your views here.

def advert(request):
    if request.method == "POST":
        return redirect('advert:ad_checkout')
    return render(request, "advert/ad_content.html")


def checkout(request):
    context = { "key":settings.STRIPE_PUBLISHABLE_KEY }
    if request.method == "POST":
        return render(request, "advert/successful_ad.html")
    return render(request, "advert/buy_ad.html", context)



def checked_out(request):
    if request.method=="POST":
        charge = stripe.Charge.create(
            amount=1000,
            currency="usd",
            description="Advert payment",
            source=request.POST['stripeToken']
        )
    return render(request, "advert/paid_ads.html")
    

Main/templates/advert/ad_content.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  iShout | Tell us more
{% endblock %}



{% block content %}
    <section class="hero-wrap" style="height: 65px; background-image: url({% static 'images/background.jpg' %});">
    </section>
    <section>
    <section class="container" style="display:flex; justify-content:center;">

        <div class="comment-form-wrap pt-5">
            <h3 class="mb-5" style="font-size: 20px; font-weight: bold;">Give us a little detail</h3>
            <form class="p-5 bg-light" method="post">
                {% csrf_token %}
              <div class="form-group">
                <label for="type">What kind of ad is it? What name would you generally tag it with? *</label>
                <input name="type" id="type" required class="form-control">
              </div>
              <div class="form-group">
                <label for="description">Description (just a short description, you would give the full advert body after our review make sure you tell us what exactly the ad is about and nothing more) *</label>
                <textarea name="description" id="description" required rows="5" class="form-control"></textarea>
              </div>
              <div class="form-group">
                <input type="submit" value="Submit" class="btn py-3 px-4 btn-primary">
              </div>

            </form>
          </div>
    </section>
{% endblock %}

Main/templates/advert/buy_ad.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  iShout | Ready to rumble? :)
{% endblock %}



{% block content %}
    <section class="hero-wrap" style="height: 65px; background-image: url({% static 'images/background.jpg' %});">
    </section>
    <section>
    <section class="container" style="display:flex; justify-content:center;">
        <div class="p-4 p-md-5" style="margin-top:40px;">
        <h3>Viola! You're all in</h3>
        <p  style="margin-bottom:10px;">We have reviewed your ad and it does not go against our policy,
        you should kick-start your popularity by buying an ad space</p>
        <form method="post">
			    {% csrf_token %}
          <script src="https://www.paypal.com/sdk/js?client-id=AePhuBYR_SPb5IEGjJU_zbXvg3e968KzpOiN428IrHMrV4fj5R4ploEjKYhnacpulC_M7mhkkCFa_lAF&currency=USD"> // Required. Replace YOUR_CLIENT_ID with your sandbox client ID.
          </script>
          <div id="paypal-button-container"></div>
          <script>
        // Render the PayPal button into #paypal-button-container
        paypal.Buttons({

            // Set up the transaction
            createOrder: function(data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: '10'
                        }
                    }]
                });
            },

            // Finalize the transaction
            onApprove: function(data, actions) {
                return actions.order.capture().then(function(details) {
                    // Show a success message to the buyer
                    window.location = "{% url 'advert:checked_out' %}";
                });
            }
        }).render('#paypal-button-container');
    </script>
        </form>


        <form method="post" action="{% url 'advert:checked_out' %}">
          {% csrf_token %}
          <h3>Pay via Stripe</h3>
          <script src="https://checkout.stripe.com/checkout.js"
            class="stripe-button"
            data-key="{{ key }}"
            data-description="Confirm payment"
            data-amount="1000"
            data-locale="auto">
          </script>
        </form>
     </div>
    </section>
{% endblock %}

Main/templates/advert/paid_ads.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  iShout | Now give us the gist
{% endblock %}



{% block content %}
    <section class="hero-wrap" style="height: 65px; background-image: url({% static 'images/background.jpg' %});">
    </section>
    <section>
    <section class="container" style="display:flex; justify-content:center;">

        <div class="comment-form-wrap pt-5">
            <h3 class="mb-5" style="font-size: 20px; font-weight: bold;">You have successfully bought your ad space. Now drop it the exact way you want</h3>
            <form class="p-5 bg-light" method="post" action="{% url 'advert:ad_checkout' %}">
                {% csrf_token %}
              <div class="form-group">
                <label for="type">Title *</label>
                <input name="type" id="type" required class="form-control">
              </div>
              <div class="form-group">
                <label for="type1">Some more intro (optional)</label>
                <input name="type1" id="type1" class="form-control">
              </div>
              <div class="form-group">
                <label for="type2">Some beautiful images (optional)</label>
                <input name="type2" id="type2" type="file" class="form-control">
              </div>
              <div class="form-group">
                <label for="description">Description (The body of your advert) *</label>
                <textarea name="description" id="description" required rows="5" max=5 class="form-control"></textarea>
              </div>
              <div class="form-group">
                <input type="submit" value="Submit" class="btn py-3 px-4 btn-primary">
              </div>

            </form>
          </div>
    </section>
{% endblock %}

Main/templates/advert/successful_ad.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  iShout | Tell us more
{% endblock %}



{% block content %}
    <section class="hero-wrap" style="height: 65px; background-image: url({% static 'images/background.jpg' %});">
    </section>
    <section>
    <section class="container" style="display:flex; justify-content:center;">

        <div class="comment-form-wrap pt-5">
            <h3>Your ad has been placed successfully</h3>
          </div>
    </section>
{% endblock %}