Comment/urls.py
from django.urls import path
from Comment import views

app_name = "comment"
urlpatterns = [
    path('<int:pk>/96/replies', views.replies, name="replies"),
    path('<parent>-new/<parent_id>/', views.create, name="create"),
    path('<int:pk>/14/reply/edit/', views.edit, name="edit"),
    path('<int:pk>/32/delete/', views.delete, name="delete")
]

Main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render

def home(request):
    # your view logic here
    return render(request, 'home.html')  # adjust the template name as needed


def home(request):

    return render(request, 'base.html')  # adjust the template name as needed

urlpatterns = [
    path('admin/', admin.site.urls),
    path('forum/',home ,name = 'home'),
    path('', include('Post.urls', namespace="post")),
    path('profile/', include('allauth.urls')),
    path('ads/', include('advert.urls', namespace="advert")),
    path('comment/', include('Comment.urls', namespace="comment")),
]

Post/urls.py
from django.urls import path
from Post import views


app_name = "post"
urlpatterns = [
    path('', views.home, name="home"),
    path('<tag_slug>/', views.home, name="home"),
    path('<int:pk>/<slug:slug>/detail/', views.detail, name="detail"),
    path('213/2444376611987366/', views.profile, name="profile"),
    path('post/new/', views.create, name="create"),
    path('<int:pk>/<slug:slug>/edit/', views.edit, name="edit"),
    path('<int:pk>/<slug:slug>/delete/', views.delete, name="delete")
]

advert/urls.py
from django.urls import path
from advert import views

app_name = "advert"
urlpatterns = [
    path('advert/', views.advert, name="advert"),
    path('checkout/', views.checkout, name="ad_checkout"),
    path('checked_out/', views.checked_out, name="checked_out"),
]

Comment/models.py
from django.db import models
from Post.models import Post
from django.contrib.auth.models import User

# Create your models here.

class Comment(models.Model):
    STATUS_CHOICES = (
        ('active', 'Active'),
        ('inactive', 'Inactive')
    )
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='comments')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default="inactive")
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True, blank=True)
    published = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    body = models.TextField()

    def __str__(self):
        return f"{self.author} {self.body[:25]}"
        
        



Post/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.contrib.auth.models import User
from taggit.managers import TaggableManager

# Create your models here.
class Post(models.Model):

    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique_for_date='published', blank=True)
    detail = models.TextField()
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='posts')
    status = models.CharField(choices=STATUS_CHOICES, max_length=10, default='draft')
    published = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    tags = TaggableManager()

    class Meta:
        ordering = ('-published',)
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("post:detail", kwargs={"pk": self.pk, "slug":self.slug})
    
    def __str__(self):
        return self.title
    

Post/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User
from django.shortcuts import redirect
from .models import Post
from taggit.models import Tag
from django.db.models import Count
from django.contrib.auth.decorators import login_required

# Create your views here.

#Home view - index.html
def home(request, tag_slug=None):
    posts = Post.objects.filter(status='published')[:12]
    
    post_count = Post.objects.count()
    user_count = User.objects.count()
    tag = None
    if  tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        posts = Post.objects.filter(status="published", tags__in=[tag])
    context = {"posts":posts, "tag":tag, "post_count":post_count, "user_count":user_count}
    return render(request, "post/index.html", context)


#For post details
def detail(request, pk, slug):
    post = get_object_or_404(Post, id=pk, slug=slug)
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.objects.filter(status='published', tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-published')[:4]
    context = {"post":post, 'similar_posts':similar_posts}
    return render(request, "post/details.html", context)


#Create new blog-post
@login_required
def create(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        slug = request.POST.get('slug')
        detail = request.POST.get('detail')
        status = request.POST.get('status')

        if title and detail:
            p = Post.objects.create(title=title, slug=slug, detail=detail, status=status, author=request.user)
            return redirect(p.get_absolute_url())
    return render(request, "post/create.html")

    
#Edit blog-post
@login_required
def edit(request, pk, slug):
    post = get_object_or_404(Post, id=pk, slug=slug)
    context = {'post':post}
    if request.method == "POST":
        title = request.POST.get('title')
        detail = request.POST.get('detail')
        status = request.POST.get('status')

        if title and detail:
            post.title=title
            post.detail=detail
            post.status=status
            post.save()
            return redirect(post.get_absolute_url())
        
    return render(request, "post/edit.html", context)


@login_required
def delete(request, pk, slug):
    post = get_object_or_404(Post, id=pk, slug=slug)
    context = {'post':post}
    if request.method == "POST":
        post.delete()
        return redirect("post:home")
        
    return render(request, "post/delete.html", context)


@login_required
def profile(request):
    drafts = request.user.posts.filter(status="draft")
    shouts = request.user.posts.filter(status="published")
    context = {"drafts":drafts, "shouts":shouts}

    return render(request, "post/profile.html", context)

Main/templates/post/create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  iShout | Shout out!!
{% endblock %}



{% block content %}
    <section class="hero-wrap" style="height: 65px; background-image: url({% static 'images/background.jpg' %});">
    </section>
    <section class="container">

        <div class="comment-form-wrap pt-5">
            <h3 class="mb-5" style="font-size: 20px; font-weight: bold;">Now its time to be heard!!</h3>
            <form class="p-5 bg-light" method="post">
                {% csrf_token %}
              <div class="form-group">
                <label for="title">Title *</label>
                <input type="text" required class="form-control" name="title" id="title">
              </div>

              <div class="form-group">
                <label for="status">Status</label>
                <select class="form-control" id="status" name="status">
                    <option value="draft">Not done? Save your shout in your profile till youre ready</option>
                    <option value="published">Shout out loud!!</option>
                </select>
              </div>

              <div class="form-group">
                <label for="detail">Please tell us more :) *</label>
                <textarea required name="detail" id="detail" cols="30" rows="10" class="form-control"></textarea>
              </div>
              <div class="form-group">
                <input type="submit" value="Shout out!" class="btn py-3 px-4 btn-primary">
              </div>

            </form>
          </div>
    </section>
{% endblock %}

Main/templates/post/delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  iShout | Delete
{% endblock %}


{% block content %}
<section class="hero-wrap" style="height: 65px; background-image: url({% static 'images/background.jpg' %}); margin-bottom:60px;">
</section>
<section class="container" style="display:flex; justify-content:center; box-shadow:0px 0px 5px black; width:280px;">
    <div>
        <h3 style="font-weight:bold; margin-bottom:40px; font-family:monospace">ARE YOU SURE?</h3>
        <form method="post">
            {% csrf_token %}
            <div class="form-group" style="display:flex; justify-content:space-between;">
                <input type="submit" style="margin-right:10px;" value="DELETE" class="btn py-3 px-4 btn-danger">
                <a style="margin-left:10px;" href="{{ post.get_absolute_url }}" class="btn py-3 px-4 btn-success">EXIT</a>
            </div>
        </form>
    </div>
</section>
{% endblock %}

Main/templates/post/details.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
  iShout | {{ post.title|truncatechars:15 }}
{% endblock %}


{% block content %}
<section class="hero-wrap" style="height: 65px; background-image: url({% static 'images/background.jpg' %});">
</section>

<section class="ftco-section ftco-no-pt ftco-no-pb">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 ftco-animate py-md-5 mt-md-5">
        <h2 class="mb-3">{{ post.title }}</h2>
        <p style="margin:0px;">
          <span style="margin-right:7px;"><span class="fa fa-calendar mr-2"></span>{{ post.published }}</span>
          <span style="margin-right:7px; text-transform:capitalize;"><span class="fa fa-user mr-2"></span>{{ post.author }}</span>
          <span style="margin-right:7px;"><span class="fa fa-comment mr-2"></span>{{ post.comment_set.count }}</span>
        </p>
        <div style="display:flex; justify-content:space-between;">
          <span>Updated: {{ post.updated }}</span>
          <span>
            {% if request.user == post.author %}
            <a href="{% url 'post:edit' pk=post.pk slug=post.slug %}">Edit shout</a>
            <a href="{% url 'post:delete' pk=post.pk slug=post.slug %}" style="margin-left:10px;">Delete shout</a>
            {% endif %}
          </span>
        </div>
        
        <p style="margin-top:15px;">{{ post.detail }}</p>
          
        <div class="tag-widget post-tag-container mb-5 mt-5">
          <div class="tagcloud">
            {% for tag in post.tags.all %}
              <a href="{% url 'post:home' tag.slug %}" style="padding:6px;" class="tag-cloud-link">{{ tag.name }}</a>
            {% endfor %}
          </div>
        </div>

         


        
        <div class="pt-5 mt-5">
          <a href="{% url 'comment:create' parent_id=post.id parent='post' %}?next={{ request.get_full_path }}" style="box-shadow:0px 0px 6px black; margin-bottom:15px;" class="btn">Comment</a>
          <h3 class="mb-5" style="font-size: 20px; font-weight: bold;">{{ post.comment_set.count }} comment{{ post.comment_set.count|pluralize }}</h3>

          <ul class="comment-list">
          {% for comment in post.comment_set.all %}
            <li class="comment">
              <div class="" style="width: calc(100% - 80px);">
                <h3 style="font-size: 16px; font-weight: 600; text-transform: capitalize;">
                  {% if not comment.author %}
                    Anonymous
                  {% else %}
                    {{ comment.author }}
                  {% endif %}
                </h3>
                <div class="meta" style="text-transform: capitalize; font-size: 12px; letter-spacing: .1em; color: #4986fc; display: block; margin-bottom: 10px;">
                  <div>{{ comment.published }}</div>
                  <div>Updated: {{ comment.updated }}</div>
                </div>
                <p>{{ comment.body }}</p>
                <p>
                  {% if comment.comment_set.all %}{{ comment.comment_set.count }} repl{{ comment.comment_set.count|pluralize:"y,ies" }} <a href="{% url 'comment:replies' comment.id %}" style="margin-right:15px;">View replies</a>{% endif %}
                  <a href="{% url 'comment:create' parent_id=comment.id parent='comment' %}?next={{ request.get_full_path }}" style="margin-right:7px;">Reply</a>
                  {% if comment.author == request.user %}
                    <a href="{% url 'comment:edit' pk=comment.pk %}?next={{ request.get_full_path }}" style="margin-right:7px;">Edit</a>
                    <a href="{% url 'comment:delete' pk=comment.pk %}?next={{ request.get_full_path }}">Delete</a>
                  {% endif %}
                </p>
              </div>
            </li>
          {% endfor %}
          </ul>

        </div>
          <!-- END comment-list -->
      </div><!-- .col-md-8 -->

    
      <div class="col-lg-4 sidebar ftco-animate pl-md-4 py-md-5">
        <div class="sidebar-box mt-md-5 bg-light">
          <form action="#" class="search-form">
            <div class="form-group">
              <span class="icon fa fa-search"></span>
              <input type="text" class="form-control" placeholder="Search...">
            </div>
          </form>
        </div>
          <h3>Similar posts</h3>
        <div class="sidebar-box ftco-animate">
          <div class="block-21 mb-4 d-flex"><div class="text">
            {% for post in similar_posts %}
              <div style="margin-bottom:30px;">
                <h3 class="heading"><a href="{% url 'post:detail' pk=post.id slug=post.slug %}">{{ post.title }}</a></h3>
                <p>{{ post.detail|truncatechars:55 }}</p>
                <div class="meta">
                  <div><span style="margin-right:5px;"><span class="fa fa-calendar"></span> {{ post.published }}</span></div>
                  <div><span style="margin-right:5px; text-transform:capitalize;"><span class="fa fa-user"></span> {{ post.author }}</span></div>
                </div>
              </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

Main/templates/post/edit.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  iShout | Shout out
{% endblock %}


{% block content %}
    <section class="hero-wrap" style="height: 65px; background-image: url({% static 'images/background.jpg' %});">
    </section>
    <section class="container">

        <div class="comment-form-wrap pt-5">
            <h3 class="mb-5" style="font-size: 20px; font-weight: bold;">Now its time to be heard!!</h3>
            <form class="p-5 bg-light" method="post">
                {% csrf_token %}
              <div class="form-group">
                <label for="title">Title *</label>
                <input type="text" required class="form-control" name="title" id="title" value="{{ post.title }}">
              </div>

              <div class="form-group">
                <label for="status">Status</label>
                <select class="form-control" id="status" name="status">
                    <option value="draft">Not done? Save your shout in your profile till youre ready</option>
                    <option value="published" {% if post.status == 'published' %}selected{% endif %}>Shout out loud!!</option>
                </select>
              </div>

              <div class="form-group">
                <label for="detail">Please tell us more :) *</label>
                <textarea required name="detail" id="detail" cols="30" rows="10" class="form-control">{{ post.detail }}</textarea>
              </div>
              <div class="form-group">
                <input type="submit" value="Edit shout!" class="btn py-3 px-4 btn-primary">
              </div>

            </form>
          </div>
    </section>
{% endblock %}

Main/templates/post/index.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
  iShout | Forums
{% endblock %}


{% block content %}

<div class="hero-wrap js-fullheight" style="background-image: url('{% static 'images/background.jpg' %}');">
  <div class="overlay"></div>
  <div class="container">
    <div class="row no-gutters slider-text js-fullheight align-items-center" data-scrollax-parent="true">
      <div class="col-md-7 ftco-animate">
        <span class="" style="color:#4986fc">MyGraduan forums</span>
        <h1 class="mb-4" style="color:#4986fc">THE PREMIER CAREER PLATFORM</h1>
        <p class="caps" style="color:white">GRADUAN is the leading and most trusted career resource for Malaysian talent,
           guiding them in their journey to become part of Malaysia’s energetic workforce.
            It is also the preferred partner for leading Malaysian employers when it comes to talent recruitment and employer branding, helping organisations find their next-generation of leaders.</p>
        <p class="mb-0"><a href="{% url 'post:create' %}" class="btn" style="color:white; background: linear-gradient(135deg, #207ce5 2%, #ce4be8 80%, #207ce5 100%);">Shout out</a> <a href="{% url 'advert:advert' %}" class="btn btn-white">Place ads</a></p>
    </div>
</div>
</div>
</div>
{% if not user.is_authenticated %}
<section class="ftco-section ftco-no-pb ftco-no-pt">
   <div class="container">
      <div class="row">
         <div class="col-md-7"></div>
         <div class="col-md-5 order-md-last">
          <div class="login-wrap p-4 p-md-5">
              <h3 class="mb-4">Sign up</h3>
              <form action="{% url 'account_signup' %}" method="post" class="signup-form">
                 {% csrf_token %}
                 <div class="form-group">
                    <label class="label" for="username">Username</label>
                    <input type="text" class="form-control" placeholder="Username" name="username">
                </div>
                <div class="form-group">
                    <label class="label" for="email">Email Address</label>
                    <input type="text" class="form-control" placeholder="Email Address" name="email">
                </div>
                <div class="form-group">
                 <label class="label" for="password">Password</label>
                 <input id="password-field" type="password" name="password1" class="form-control" placeholder="Password">
             </div>
             <div class="form-group">
                 <label class="label" for="password">Confirm Password</label>
                 <input id="password-field" type="password" name="password2" class="form-control" placeholder="Confirm Password">
             </div>
             <div class="form-group d-flex justify-content-end mt-4">
                 <button type="submit" class="btn btn-primary submit"><span class="fa fa-paper-plane"></span></button>
             </div>
         </form>
         <p class="text-center">Already have an account? <a href="{% url 'account_login' %}">Sign In</a></p>
     </div>
 </div>
</div>
</div>
</section>

{% endif %}





<section class="ftco-section bg-light">
  {% if tag %}
    <div class="row justify-content-center pb-4 col-md-12 heading-section text-center ftco-animate">
      <h2 class="mb-4">Posts tagged with "{{ tag.name }}"</h2>
    </div>
  {% elif not tag %}
  <div class="container" id="recent">
     <div class="row justify-content-center pb-4 col-md-12 heading-section text-center ftco-animate">
         <h2 class="mb-4">Recent Posts</h2>
     </div>
 </div>
 {% endif %}
 <div class="row d-flex">
  {% for post in posts %}
    <div class="col-lg-4 ftco-animate">
      <div class="blog-entry">
        <div class="text d-block">
          <div class="meta">
            <p>
              <span style="margin-right:2px;"><span class="fa fa-calendar mr-2"></span>{{ post.published }}</span>
              <span style="margin-right:2px;"><span class="fa fa-user mr-2"></span>{{ post.author }}</span>
              <span style="margin-right:2px;"><span class="fa fa-comment mr-2"></span>{{ post.comment_set.count }}</span>
          </p>
      </div>
      <h3 class="heading"><a href="{% url 'post:detail' pk=post.id slug=post.slug %}">{{ post.title }}</a></h3>
      <p>{{ post.detail|truncatechars:55 }}</p>
      <p><a href="{% url 'post:detail' pk=post.id slug=post.slug %}" class="btn btn-secondary py-2 px-3">Read more</a></p>
  </div>
  </div>
  </div>
{% endfor %}

</div>
</div>
</section>





{% endblock %}

Main/templates/post/profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  myGraduan | {{ user.username }} - Profile
{% endblock %}



{% block content %}
    <section class="hero-wrap" style="height: 65px; background-image: url({% static 'images/background.jpg' %});">
    </section>
    <section>
    <div class="container">
      <div style="margin: 30px 0px 0px 30px;">
        Hello {{ user.username }}! 
        <h3 style="font-weight:bold; text-align:center;">Shouts!</h3>
      </div>
      <div class="row d-flex">
            {% if shouts %}
                {% for post in shouts %}
                <div class="col-lg-4 ftco-animate">
                    <div class="blog-entry">
                        <div class="text d-block">
                            <div class="meta">
                                <p>
                                    <span style="margin-right:2px;"><span class="fa fa-calendar mr-2"></span>{{ post.published }}</span>
                                    <span style="margin-right:2px;"><span class="fa fa-user mr-2"></span>{{ post.author }}</span>
                                    <span style="margin-right:2px;"><span class="fa fa-comment mr-2"></span>{{ post.comment_set.count }}</span>
                                </p>
                            </div>
                            <h3 class="heading"><a href="{% url 'post:detail' pk=post.id slug=post.slug %}">{{ post.title }}</a></h3>
                            <p>{{ post.detail|truncatechars:55 }}</p>
                            <p><a href="{% url 'post:detail' pk=post.id slug=post.slug %}" class="btn btn-secondary py-2 px-3">Read more</a></p>
                        </div>
                    </div>
                    </div>
                {% endfor %}
            {% else %}
                Your shouts would be shown here! You should  <a href="{% url 'post:create' %}" class="btn" style="border-radius:0px; color:white; background:#ddd; padding:1px 4px;">Shout out</a> now
            {% endif %}
        </div>
    <div>
      <div>
        <h3 style="font-weight:bold; text-align:center;">Drafts!</h3>
      </div>
            {% if drafts %}
                {% for post in drafts %}
                <div class="col-lg-4 ftco-animate">
                    <div class="blog-entry">
                        <div class="text d-block">
                            <div class="meta">
                                <p>
                                    <span style="margin-right:2px;"><span class="fa fa-calendar mr-2"></span>{{ post.published }}</span>
                                    <span style="margin-right:2px;"><span class="fa fa-user mr-2"></span>{{ post.author }}</span>
                                    <span style="margin-right:2px;"><span class="fa fa-comment mr-2"></span>{{ post.comment_set.count }}</span>
                                </p>
                            </div>
                            <h3 class="heading"><a href="{% url 'post:detail' pk=post.id slug=post.slug %}">{{ post.title }}</a></h3>
                            <p>{{ post.detail|truncatechars:55 }}</p>
                            <p><a href="{% url 'post:detail' pk=post.id slug=post.slug %}" class="btn btn-secondary py-2 px-3">Read more</a></p>
                        </div>
                    </div>
                    </div>
                {% endfor %}
            {% else %}
                Your drafts would be saved here!
            {% endif %}
          </div>
  </div>
    </section>
{% endblock %}