Main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render

def home(request):
    # your view logic here
    return render(request, 'home.html')  # adjust the template name as needed


def home(request):

    return render(request, 'base.html')  # adjust the template name as needed

urlpatterns = [
    path('admin/', admin.site.urls),
    path('forum/',home ,name = 'home'),
    path('', include('Post.urls', namespace="post")),
    path('profile/', include('allauth.urls')),
    path('ads/', include('advert.urls', namespace="advert")),
    path('comment/', include('Comment.urls', namespace="comment")),
]

Post/urls.py
from django.urls import path
from Post import views


app_name = "post"
urlpatterns = [
    path('', views.home, name="home"),
    path('<tag_slug>/', views.home, name="home"),
    path('<int:pk>/<slug:slug>/detail/', views.detail, name="detail"),
    path('213/2444376611987366/', views.profile, name="profile"),
    path('post/new/', views.create, name="create"),
    path('<int:pk>/<slug:slug>/edit/', views.edit, name="edit"),
    path('<int:pk>/<slug:slug>/delete/', views.delete, name="delete")
]

advert/urls.py
from django.urls import path
from advert import views

app_name = "advert"
urlpatterns = [
    path('advert/', views.advert, name="advert"),
    path('checkout/', views.checkout, name="ad_checkout"),
    path('checked_out/', views.checked_out, name="checked_out"),
]

Main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.timepicker.css' %}">
    
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">


    <style>
      
      @media (min-width: 460px) {
        .stupid-auth-form{
          max-width: 258px;
        }
      }
    </style>
</head>
<body>
 <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
   <div class="container">
     <a class="navbar-brand" href="{% url 'post:home' %}"><span>MyGraduan</span></a>
     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
       <span class="oi oi-men"></span>menu
   </button>

   <div class="collapse navbar-collapse" id="ftco-nav">
       <ul class="navbar-nav ml-auto">
         <li class="nav-item"><a href="{% url 'post:home' %}" class="nav-link">Home</a></li>
         {% if not user.is_authenticated %}
            <li class="nav-item"><a href="{% url 'account_login' %}" class="nav-link">Sign in</a></li>
            <li class="nav-item"><a href="{% url 'account_signup' %}" class="nav-link">Sign up</a></li>
         {% else %}
            <li class="nav-item"><a href="{% url 'post:profile' %}" class="nav-link">Profile</a></li>
            <li class="nav-item"><a href="{% url 'account_logout' %}" class="nav-link">Log out</a></li>
         {% endif %}
         <li class="nav-item"><a href="{% url 'post:create' %}" style="color:#4986fc; font-weight:bold;" class="nav-link">Shout out!</a></li>
     </ul>
 </div>
</div>
</nav>
<!-- END nav -->






{% block content %}
{% endblock %}










<section class="ftco-section services-section">
  <div class="container" id="advertise">
        <h2 class="mb-4" style="text-align:center; font-family:monaspace;">Advertise with us</h2>
    <div class="row d-flex">
      <div class="col-md-6 heading-section pr-md-5 ftco-animate d-flex align-items-center">
         <div class="w-100 mb-4 mb-md-0">
             <img style="width:100%;" src="{% static 'images/snapshot.jpg' %}">
     </div>
 </div>
 <div class="col-md-6">
     <div class="row">
        <div class="col-md-12 col-lg-6 d-flex align-self-stretch ftco-animate">
          <div class="services">
            <div class="icon d-flex align-items-center justify-content-center"><span class="flaticon-tools"></span></div>
            <div class="media-body">
              <h3 class="heading mb-3">Widespread Audience</h3>
              <p>With our enormous community, we can give you the satisfation of reaching out your product to your targetted audience</p>
          </div>
      </div>      
  </div>
<div class="col-md-12 col-lg-6 d-flex align-self-stretch ftco-animate">
  <div class="services">
    <div class="icon icon-4 d-flex align-items-center justify-content-center"><span class="flaticon-browser"></span></div>
    <div class="media-body">
      <h3 class="heading mb-3">Easy approval</h3>
      <p>With our artificial intelligence screening system, you can get your ads screened and placed in a few minutes</p>
  </div>
</div>      
</div>
</div>
</div>
</div>
</div>
</section>





<section class="ftco-section ftco-counter img" id="section-counter" style="background-image: url({%static 'images/bg_4.jpg' %});">
 <div class="overlay"></div>
 <div class="container">
    <div class="row">
       <div class="col-md-3 d-flex justify-content-center counter-wrap ftco-animate">
         <div class="block-18 d-flex align-items-center">
            <div class="text">
             <strong class="number">Stats:</strong>
             <span></span>
         </div>
     </div>
 </div>
 <div class="col-md-3 d-flex justify-content-center counter-wrap ftco-animate">
     <div class="block-18 d-flex align-items-center">
        <div class="text">
         <strong class="number" data-number="22">0</strong>
         <span>Topics</span>
     </div>
 </div>
</div>
<div class="col-md-3 d-flex justify-content-center counter-wrap ftco-animate">
 <div class="block-18 d-flex align-items-center">
    <div class="text">
     <strong class="number" data-number="37">0</strong>
     <span>Members</span>
 </div>
</div>
</div>
<div class="col-md-3 d-flex justify-content-center counter-wrap ftco-animate">
 <div class="block-18 d-flex align-items-center">
    <div class="text">
     <strong class="number" data-number="16">0</strong>
     <span>Online</span>
 </div>
</div>
</div>
</div>
</div>
</section>






<footer class="ftco-footer ftco-no-pt">
  <div class="container">
      <div style="padding-bottom: 20px;"></div>
      <h2 class="ftco-heading-2" style="font-weight:bold; text-align:center;">Quick links</h2>
      <ul class="list-unstyled" style="display:flex; justify-content:center;">
        <li style="display:inline; margin-right:25px; font-weight:bold;"><a href="{% url 'post:home' %}#recent" class="">Recent</a></li>
        <li style="display:inline; margin-right:25px; font-weight:bold;"><a href="{% url 'advert:advert' %}" class="">Advertise With Us</a></li>
        <li style="display:inline; margin-right:25px; font-weight:bold;"><a href="#" class="">Privacy Policy</a></li>
    </ul>
  </div>

  <p class="text-center" style="margin-top:30px; font-size:13px;">
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
      Copyright &copy;<script>document.write(new Date().getFullYear());</script> Made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
      <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  </p>
</div>
</footer>



<!-- loader -->
<div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
<script src="{% static 'js/scrollax.min.js' %}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
<script src="{% static 'js/google-map.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

</body>
</html>